[package]
name = "wtaskman"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]

[dependencies]
web-view = "0.1.3"
urlencoding = "1.0.0"
serde = "1.0.27" 
serde_derive = "1.0.27" 
serde_json = "1.0.10"
procinfo = "0.4.2"